export type RootStackParamList = {
  MainTabs: undefined;
  NewRepair: { customerName?: string; customerPhone?: string; deviceModel?: string; initialIssue?: string } | undefined;
  CustomerList: undefined;
  RepairDetail: { repairId: number };
  PartForm: { partId?: number };
  Restock: { partId: number; partName: string; costPrice: number };
  BulkRestock: { partIds: number[] };
  CustomerDetail: { customerId: number };
  InvoicePreview: { invoiceId: number; type: 'repair' | 'device_sale' };
  InvoiceHistory: undefined;
  CategoryList: undefined;
  DeviceBrandList: undefined;
  DeviceModelList: undefined;
  IssueList: undefined;
  ShopInfo: undefined;
  Backup: undefined;
  StaffList: undefined;
  StaffPerformance: { staffId?: number };
  SupplierDetail: { supplierId: number };
  CoTechDetail: { coTechId: number };
  License: undefined;
  PriceInquiry: undefined;
  ShopeeSearch: { query?: string; storeUrl?: string; title?: string } | undefined;
  Quotation: undefined;
  ExpenseDetail: { period: import('../repositories/reportsRepository').ReportPeriod; targetDate?: string; dateTo?: string };
  FinancialDetail: { kind: import('../repositories/reportsRepository').FinancialKind; period: import('../repositories/reportsRepository').ReportPeriod; targetDate?: string; dateTo?: string };
  DeviceSaleForm: { deviceModel?: string } | undefined;
  DevicePurchaseForm: undefined;
  DevicesList: undefined;
  DeviceSaleDetail: { saleId: number };
  SyncSetup: undefined;
  Consumables: undefined;
};

export type TabParamList = {
  Dashboard: undefined;
  Customers: undefined;
  Repairs: { initialFilter?: string; dateFrom?: string; dateTo?: string } | undefined;
  Parts: undefined;
  Suppliers: undefined;
  CoTech: undefined;
  More: undefined;
};
